=== mac46005/WebProgramming_CMP_SCI3010/Modules/M6_xml/userModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="userModel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:positiveInteger"></xs:element>
                <xs:element name="userName" type="xs:string"></xs:element>
                <xs:element name="password" type="xs:string"></xs:element>
                <xs:element name="firstName" type="xs:string"></xs:element>
                <xs:element name="lastName" type="xs:string"></xs:element>
                <xs:element name="address01" type="xs:string"></xs:element>
                <xs:element name="address02" type="xs:string"></xs:element>
                <xs:element name="city" type="xs:string"></xs:element>
                <xs:element name="state"></xs:element>
                <xs:element name="zip" type="xs:string"></xs:element>
                <xs:element name="phoneNumber" type="xs:string"></xs:element>
                <xs:element name="email" type="xs:string"></xs:element>
                <xs:element name="gender" type="xs:string"></xs:element>
                <xs:element name="maritalStatus" type="xs:string"></xs:element>
                <xs:element name="dob" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mac46005/WebProgramming_CMP_SCI3010/Modules/M6_xml/newUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<userModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./userModel.xsd">
    <id>4</id>
    <userName>mac46005</userName>
    <password>Dollfacelover2021!</password>
    <firstName>Marco</firstName>
    <lastName>Preciado</lastName>
    <address01>1503 Wildhorse Pkwy Dr.</address01>
    <address02></address02>
    <city>Saint Louis</city>
    <state>MO</state>
    <zip>63005</zip>
    <phoneNumber>3148858641</phoneNumber>
    <email>mac46005@gmail.com</email>
    <gender>Male</gender>
    <maritalStatus>Married</maritalStatus>
    <dob>12/19/1992</dob>
</userModel>
